 spring:
  datasource: #数据库源
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jpatest?characterEncoding=UTF-8&&useSSL=true
    username: root
    password:
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计，'wall'用于防火墙
    #监控统计用的filter:stat;日志用的filter:log4j;防御sql注入的filter:wall
    filters: stat,wall,log4j
    maxActive: 20 #最大活跃数
    initialSize: 1 #初始化数量
    maxWait: 60000 #最大连接等待时间
    poolPreparedStatement: true #打开PSCache
    maxPoolPreparedStatementPerConnections: 20 #指定每个连接PSCache的大小
    #通过connectionProperties属性来打开mergeSql功能；慢SQL纪录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    timeBetweenEvictionRunsMills: 60000
    minEvictableIdeleTimeMills: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false


  jpa: #jpa数据操作
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    database: mysql